INSERT INTO guitarists (position, guitarist, genre) VALUES (1,"Jimi Hendrix", "Classic Rock");
INSERT INTO guitarists (position, guitarist, genre) VALUES (2,"Eric Clapton", "Classic Rock");
INSERT INTO guitarists (position, guitarist, genre) VALUES (3,"Jimmy Page", "Classic Rock");
INSERT INTO guitarists (position, guitarist, genre) VALUES (4,"Keith Richards", "Classic Rock");
INSERT INTO guitarists (position, guitarist, genre) VALUES (5,"Jeff Beck", "Classic Rock");
INSERT INTO guitarists (position, guitarist, genre) VALUES (6,"B.B. King", "Blues");
INSERT INTO guitarists (position, guitarist, genre) VALUES (7,"Chuck Berry", "Rock N Roll");
INSERT INTO guitarists (position, guitarist, genre) VALUES (8,"Eddie Van Halen", "Metal");
INSERT INTO guitarists (position, guitarist, genre) VALUES (9,"Duane Allman", "Classic Rock");
INSERT INTO guitarists (position, guitarist, genre) VALUES (10,"Pete Townshend", "Classic Rock");
INSERT INTO guitarists (position, guitarist, genre) VALUES (11,"George Harrison", "Classic Rock");
INSERT INTO guitarists (position, guitarist, genre) VALUES (12,"Stevie Ray Vaughan", "Blues");
INSERT INTO guitarists (position, guitarist, genre) VALUES (13,"Albert King", "Blues");
INSERT INTO guitarists (position, guitarist, genre) VALUES (14,"David Gilmour", "Classic Rock");
INSERT INTO guitarists (position, guitarist, genre) VALUES (15,"Freddy King", "Blues");
INSERT INTO guitarists (position, guitarist, genre) VALUES (16,"Derek Trucks", "Jam");
INSERT INTO guitarists (position, guitarist, genre) VALUES (17,"Neil Young", "Classic Rock");
INSERT INTO guitarists (position, guitarist, genre) VALUES (18,"Les Paul", "Jazz");
INSERT INTO guitarists (position, guitarist, genre) VALUES (19,"James Burton", "Rock N Roll");
INSERT INTO guitarists (position, guitarist, genre) VALUES (20,"Carlos Santana", "Classic Rock");
INSERT INTO guitarists (position, guitarist, genre) VALUES (21,"Chet Atkins", "Country");
INSERT INTO guitarists (position, guitarist, genre) VALUES (22,"Frank Zappa", "Classic Rock");
INSERT INTO guitarists (position, guitarist, genre) VALUES (23,"Buddy Guy", "Blues");
INSERT INTO guitarists (position, guitarist, genre) VALUES (24,"Angus Young", "Classic Rock");
INSERT INTO guitarists (position, guitarist, genre) VALUES (25,"Tony Iommi", "Metal");
INSERT INTO guitarists (position, guitarist, genre) VALUES (26,"Brian May", "Classic Rock");
INSERT INTO guitarists (position, guitarist, genre) VALUES (27,"Bo Diddley", "Rock N Roll");
INSERT INTO guitarists (position, guitarist, genre) VALUES (28,"Johnny Ramone", "Punk Rock");
INSERT INTO guitarists (position, guitarist, genre) VALUES (29,"Scotty Moore", "Rock N Roll");
INSERT INTO guitarists (position, guitarist, genre) VALUES (30,"Elmore James", "Blues");
INSERT INTO guitarists (position, guitarist, genre) VALUES (31,"Ry Cooder", "Blues");
INSERT INTO guitarists (position, guitarist, genre) VALUES (32,"Billy Gibbons", "Classic Rock");
INSERT INTO guitarists (position, guitarist, genre) VALUES (33,"Prince", "Funk");
INSERT INTO guitarists (position, guitarist, genre) VALUES (34,"Curtis Mayfield", "Soul");
INSERT INTO guitarists (position, guitarist, genre) VALUES (35,"John Lee Hooker", "Blues");
INSERT INTO guitarists (position, guitarist, genre) VALUES (36,"Randy Rhoads", "Metal");
INSERT INTO guitarists (position, guitarist, genre) VALUES (37,"Mick Taylor", "Classic Rock");
INSERT INTO guitarists (position, guitarist, genre) VALUES (38,"The Edge", "Classic Rock");
INSERT INTO guitarists (position, guitarist, genre) VALUES (39,"Steve Cropper", "Rock N Roll");
INSERT INTO guitarists (position, guitarist, genre) VALUES (40,"Tom Morello", "Metal");
INSERT INTO guitarists (position, guitarist, genre) VALUES (41,"Mick Ronson", "Classic Rock");
INSERT INTO guitarists (position, guitarist, genre) VALUES (42,"Mike Bloomfield", "Blues");
INSERT INTO guitarists (position, guitarist, genre) VALUES (43,"Hubert Sumlin", "Blues");
INSERT INTO guitarists (position, guitarist, genre) VALUES (44,"Mark Knopfler", "Classic Rock");
INSERT INTO guitarists (position, guitarist, genre) VALUES (45,"Link Wray", "Rock N Roll");
INSERT INTO guitarists (position, guitarist, genre) VALUES (46,"Jerry Garcia", "Jam");
INSERT INTO guitarists (position, guitarist, genre) VALUES (47,"Stephen Stills", "Classic Rock");
INSERT INTO guitarists (position, guitarist, genre) VALUES (48,"Jonny Greenwood", "Alternative");
INSERT INTO guitarists (position, guitarist, genre) VALUES (49,"Muddy Waters", "Blues");
INSERT INTO guitarists (position, guitarist, genre) VALUES (50,"Ritchie Blackmore", "Classic Rock");
INSERT INTO guitarists (position, guitarist, genre) VALUES (51,"Johnny Marr", "Atlernative");
INSERT INTO guitarists (position, guitarist, genre) VALUES (52,"Clarence White", "Folk");
INSERT INTO guitarists (position, guitarist, genre) VALUES (53,"Otis Rush", "Blues");
INSERT INTO guitarists (position, guitarist, genre) VALUES (54,"Joe Walsh", "Classic Rock");
INSERT INTO guitarists (position, guitarist, genre) VALUES (55,"John Lennon", "Classic Rock");
INSERT INTO guitarists (position, guitarist, genre) VALUES (56,"Albert Collins", "Blues");
INSERT INTO guitarists (position, guitarist, genre) VALUES (57,"Rory Gallagher", "Blues");
INSERT INTO guitarists (position, guitarist, genre) VALUES (58,"Peter Green", "Blues");
INSERT INTO guitarists (position, guitarist, genre) VALUES (59,"Robbie Robertson", "Classic Rock");
INSERT INTO guitarists (position, guitarist, genre) VALUES (60,"Ron Asheton", "Punk Rock");
INSERT INTO guitarists (position, guitarist, genre) VALUES (61,"Dickey Betts", "Classic Rock");
INSERT INTO guitarists (position, guitarist, genre) VALUES (62,"Robert Fripp", "Prog Rock");
INSERT INTO guitarists (position, guitarist, genre) VALUES (63,"Johnny Winter", "Blues");
INSERT INTO guitarists (position, guitarist, genre) VALUES (64,"Duane Eddy", "Rock N Roll");
INSERT INTO guitarists (position, guitarist, genre) VALUES (65,"Slash", "Metal");
INSERT INTO guitarists (position, guitarist, genre) VALUES (66,"Leslie West", "Classic Rock");
INSERT INTO guitarists (position, guitarist, genre) VALUES (67,"T Bone Walker", "Blues");
INSERT INTO guitarists (position, guitarist, genre) VALUES (68,"John McLaughlin", "Jazz");
INSERT INTO guitarists (position, guitarist, genre) VALUES (69,"Richard Thompson", "Folk");
INSERT INTO guitarists (position, guitarist, genre) VALUES (70,"Jack White", "Alterantive");
INSERT INTO guitarists (position, guitarist, genre) VALUES (71,"Robert Johnson", "Blues");
INSERT INTO guitarists (position, guitarist, genre) VALUES (72,"John Frusciante", "Funk");
INSERT INTO guitarists (position, guitarist, genre) VALUES (73,"Kurt Cobain", "Grunge");
INSERT INTO guitarists (position, guitarist, genre) VALUES (74,"Dick Dale", "Surf Rock");
INSERT INTO guitarists (position, guitarist, genre) VALUES (75,"Joni Mitchell", "Folk");
INSERT INTO guitarists (position, guitarist, genre) VALUES (76,"Robby Krieger", "Classic Rock");
INSERT INTO guitarists (position, guitarist, genre) VALUES (77,"Willie Nelson", "Country");
INSERT INTO guitarists (position, guitarist, genre) VALUES (78,"John Fahey", "Folk");
INSERT INTO guitarists (position, guitarist, genre) VALUES (79,"Mike Campbell", "Classic Rock");
INSERT INTO guitarists (position, guitarist, genre) VALUES (80,"Buddy Holly", "Rock N Roll");
INSERT INTO guitarists (position, guitarist, genre) VALUES (81,"Lou Reed", "Classic Rock");
INSERT INTO guitarists (position, guitarist, genre) VALUES (82,"Nels Cline", "Indie Rock");
INSERT INTO guitarists (position, guitarist, genre) VALUES (83,"Eddie Hazel", "Funk");
INSERT INTO guitarists (position, guitarist, genre) VALUES (84,"Joe Perry", "Classic Rock");
INSERT INTO guitarists (position, guitarist, genre) VALUES (85,"Andy Summers", "Classic Rock");
INSERT INTO guitarists (position, guitarist, genre) VALUES (86,"J Mascis", "Alternative");
INSERT INTO guitarists (position, guitarist, genre) VALUES (87,"James Hetfield", "Metal");
INSERT INTO guitarists (position, guitarist, genre) VALUES (88,"Carl Perkins", "Rock N Roll");
INSERT INTO guitarists (position, guitarist, genre) VALUES (89,"Bonnie Raitt", "Blues");
INSERT INTO guitarists (position, guitarist, genre) VALUES (90,"Tom Verlaine", "Punk Rock");
INSERT INTO guitarists (position, guitarist, genre) VALUES (91,"Dave Davies", "Classic Rock");
INSERT INTO guitarists (position, guitarist, genre) VALUES (92,"Dimebag Darrell", "Metal");
INSERT INTO guitarists (position, guitarist, genre) VALUES (93,"Paul Simon", "Classic Rock");
INSERT INTO guitarists (position, guitarist, genre) VALUES (94,"Peter Buck", "Alternative");
INSERT INTO guitarists (position, guitarist, genre) VALUES (95,"Roger McGuinn", "Classic Rock");
INSERT INTO guitarists (position, guitarist, genre) VALUES (96,"Bruce Springsteen", "Classic Rock");
INSERT INTO guitarists (position, guitarist, genre) VALUES (97,"Steve Jones", "Punk Rock");
INSERT INTO guitarists (position, guitarist, genre) VALUES (98,"Alex Lifeson", "Prog Rock");
INSERT INTO guitarists (position, guitarist, genre) VALUES (99,"Thurston Moore", "Alternative");
INSERT INTO guitarists (position, guitarist, genre) VALUES (100,"Lindsey Buckingham", "Classic Rock");
